module PostForMe
  module Models
    type create_social_post =
      {
        caption: String,
        social_accounts: ::Array[String],
        account_configurations: ::Array[PostForMe::AccountConfiguration]?,
        external_id: String?,
        is_draft: bool?,
        media: ::Array[PostForMe::SocialPostMedia]?,
        platform_configurations: PostForMe::PlatformConfigurationsDto?,
        scheduled_at: Time?
      }

    class CreateSocialPost < PostForMe::Internal::Type::BaseModel
      attr_accessor caption: String

      attr_accessor social_accounts: ::Array[String]

      attr_accessor account_configurations: ::Array[PostForMe::AccountConfiguration]?

      attr_accessor external_id: String?

      attr_accessor is_draft: bool?

      attr_accessor media: ::Array[PostForMe::SocialPostMedia]?

      attr_accessor platform_configurations: PostForMe::PlatformConfigurationsDto?

      attr_accessor scheduled_at: Time?

      def initialize: (
        caption: String,
        social_accounts: ::Array[String],
        ?account_configurations: ::Array[PostForMe::AccountConfiguration]?,
        ?external_id: String?,
        ?is_draft: bool?,
        ?media: ::Array[PostForMe::SocialPostMedia]?,
        ?platform_configurations: PostForMe::PlatformConfigurationsDto?,
        ?scheduled_at: Time?
      ) -> void

      def to_hash: -> {
        caption: String,
        social_accounts: ::Array[String],
        account_configurations: ::Array[PostForMe::AccountConfiguration]?,
        external_id: String?,
        is_draft: bool?,
        media: ::Array[PostForMe::SocialPostMedia]?,
        platform_configurations: PostForMe::PlatformConfigurationsDto?,
        scheduled_at: Time?
      }
    end
  end
end
