module PostForMe
  module Models
    type facebook_configuration_dto =
      {
        caption: top?,
        media: ::Array[PostForMe::FacebookConfigurationDto::Media]?,
        placement: PostForMe::Models::FacebookConfigurationDto::placement?
      }

    class FacebookConfigurationDto < PostForMe::Internal::Type::BaseModel
      attr_accessor caption: top?

      attr_accessor media: ::Array[PostForMe::FacebookConfigurationDto::Media]?

      attr_accessor placement: PostForMe::Models::FacebookConfigurationDto::placement?

      def initialize: (
        ?caption: top?,
        ?media: ::Array[PostForMe::FacebookConfigurationDto::Media]?,
        ?placement: PostForMe::Models::FacebookConfigurationDto::placement?
      ) -> void

      def to_hash: -> {
        caption: top?,
        media: ::Array[PostForMe::FacebookConfigurationDto::Media]?,
        placement: PostForMe::Models::FacebookConfigurationDto::placement?
      }

      type media =
        { url: String, thumbnail_timestamp_ms: top?, thumbnail_url: top? }

      class Media < PostForMe::Internal::Type::BaseModel
        attr_accessor url: String

        attr_accessor thumbnail_timestamp_ms: top?

        attr_accessor thumbnail_url: top?

        def initialize: (
          url: String,
          ?thumbnail_timestamp_ms: top?,
          ?thumbnail_url: top?
        ) -> void

        def to_hash: -> {
          url: String,
          thumbnail_timestamp_ms: top?,
          thumbnail_url: top?
        }
      end

      type placement = :reels | :stories | :timeline

      module Placement
        extend PostForMe::Internal::Type::Enum

        REELS: :reels
        STORIES: :stories
        TIMELINE: :timeline

        def self?.values: -> ::Array[PostForMe::Models::FacebookConfigurationDto::placement]
      end
    end
  end
end
