module PostForMe
  module Models
    type facebook_configuration_dto =
      {
        caption: top?,
        collaborators: ::Array[::Array[top]]?,
        location: String?,
        media: ::Array[PostForMe::SocialPostMedia]?,
        placement: PostForMe::Models::FacebookConfigurationDto::placement?,
        set_caption_for_each_image: bool?
      }

    class FacebookConfigurationDto < PostForMe::Internal::Type::BaseModel
      attr_accessor caption: top?

      attr_accessor collaborators: ::Array[::Array[top]]?

      attr_accessor location: String?

      attr_accessor media: ::Array[PostForMe::SocialPostMedia]?

      attr_accessor placement: PostForMe::Models::FacebookConfigurationDto::placement?

      attr_accessor set_caption_for_each_image: bool?

      def initialize: (
        ?caption: top?,
        ?collaborators: ::Array[::Array[top]]?,
        ?location: String?,
        ?media: ::Array[PostForMe::SocialPostMedia]?,
        ?placement: PostForMe::Models::FacebookConfigurationDto::placement?,
        ?set_caption_for_each_image: bool?
      ) -> void

      def to_hash: -> {
        caption: top?,
        collaborators: ::Array[::Array[top]]?,
        location: String?,
        media: ::Array[PostForMe::SocialPostMedia]?,
        placement: PostForMe::Models::FacebookConfigurationDto::placement?,
        set_caption_for_each_image: bool?
      }

      type placement = :reels | :stories | :timeline

      module Placement
        extend PostForMe::Internal::Type::Enum

        REELS: :reels
        STORIES: :stories
        TIMELINE: :timeline

        def self?.values: -> ::Array[PostForMe::Models::FacebookConfigurationDto::placement]
      end
    end
  end
end
