module PostForMe
  module Models
    type instagram_configuration_dto =
      {
        caption: top?,
        collaborators: ::Array[String]?,
        location: String?,
        media: ::Array[PostForMe::SocialPostMedia]?,
        placement: PostForMe::Models::InstagramConfigurationDto::placement?,
        share_to_feed: bool?,
        trial_reel_type: PostForMe::Models::InstagramConfigurationDto::trial_reel_type?
      }

    class InstagramConfigurationDto < PostForMe::Internal::Type::BaseModel
      attr_accessor caption: top?

      attr_accessor collaborators: ::Array[String]?

      attr_accessor location: String?

      attr_accessor media: ::Array[PostForMe::SocialPostMedia]?

      attr_accessor placement: PostForMe::Models::InstagramConfigurationDto::placement?

      attr_accessor share_to_feed: bool?

      attr_accessor trial_reel_type: PostForMe::Models::InstagramConfigurationDto::trial_reel_type?

      def initialize: (
        ?caption: top?,
        ?collaborators: ::Array[String]?,
        ?location: String?,
        ?media: ::Array[PostForMe::SocialPostMedia]?,
        ?placement: PostForMe::Models::InstagramConfigurationDto::placement?,
        ?share_to_feed: bool?,
        ?trial_reel_type: PostForMe::Models::InstagramConfigurationDto::trial_reel_type?
      ) -> void

      def to_hash: -> {
        caption: top?,
        collaborators: ::Array[String]?,
        location: String?,
        media: ::Array[PostForMe::SocialPostMedia]?,
        placement: PostForMe::Models::InstagramConfigurationDto::placement?,
        share_to_feed: bool?,
        trial_reel_type: PostForMe::Models::InstagramConfigurationDto::trial_reel_type?
      }

      type placement = :reels | :stories | :timeline

      module Placement
        extend PostForMe::Internal::Type::Enum

        REELS: :reels
        STORIES: :stories
        TIMELINE: :timeline

        def self?.values: -> ::Array[PostForMe::Models::InstagramConfigurationDto::placement]
      end

      type trial_reel_type = :manual | :performance

      module TrialReelType
        extend PostForMe::Internal::Type::Enum

        MANUAL: :manual
        PERFORMANCE: :performance

        def self?.values: -> ::Array[PostForMe::Models::InstagramConfigurationDto::trial_reel_type]
      end
    end
  end
end
