module PostForMe
  module Models
    type platform_post =
      {
        caption: String,
        media: ::Array[::Array[top]],
        platform: String,
        platform_account_id: String,
        platform_post_id: String,
        platform_url: String,
        social_account_id: String,
        external_account_id: String?,
        external_post_id: String?,
        metrics: PostForMe::Models::PlatformPost::metrics,
        posted_at: Time,
        social_post_id: String?,
        social_post_result_id: String?
      }

    class PlatformPost < PostForMe::Internal::Type::BaseModel
      attr_accessor caption: String

      attr_accessor media: ::Array[::Array[top]]

      attr_accessor platform: String

      attr_accessor platform_account_id: String

      attr_accessor platform_post_id: String

      attr_accessor platform_url: String

      attr_accessor social_account_id: String

      attr_accessor external_account_id: String?

      attr_accessor external_post_id: String?

      attr_reader metrics: PostForMe::Models::PlatformPost::metrics?

      def metrics=: (
        PostForMe::Models::PlatformPost::metrics
      ) -> PostForMe::Models::PlatformPost::metrics

      attr_reader posted_at: Time?

      def posted_at=: (Time) -> Time

      attr_accessor social_post_id: String?

      attr_accessor social_post_result_id: String?

      def initialize: (
        caption: String,
        media: ::Array[::Array[top]],
        platform: String,
        platform_account_id: String,
        platform_post_id: String,
        platform_url: String,
        social_account_id: String,
        ?external_account_id: String?,
        ?external_post_id: String?,
        ?metrics: PostForMe::Models::PlatformPost::metrics,
        ?posted_at: Time,
        ?social_post_id: String?,
        ?social_post_result_id: String?
      ) -> void

      def to_hash: -> {
        caption: String,
        media: ::Array[::Array[top]],
        platform: String,
        platform_account_id: String,
        platform_post_id: String,
        platform_url: String,
        social_account_id: String,
        external_account_id: String?,
        external_post_id: String?,
        metrics: PostForMe::Models::PlatformPost::metrics,
        posted_at: Time,
        social_post_id: String?,
        social_post_result_id: String?
      }

      type metrics =
        PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto
        | PostForMe::PlatformPost::Metrics::TikTokPostMetricsDto
        | PostForMe::PlatformPost::Metrics::InstagramPostMetricsDto
        | PostForMe::PlatformPost::Metrics::YouTubePostMetricsDto
        | PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto
        | PostForMe::PlatformPost::Metrics::TwitterPostMetricsDto
        | PostForMe::PlatformPost::Metrics::ThreadsPostMetricsDto
        | top

      module Metrics
        extend PostForMe::Internal::Type::Union

        type tik_tok_business_metrics_dto =
          {
            address_clicks: Float,
            app_download_clicks: Float,
            audience_cities: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::AudienceCity],
            audience_countries: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::AudienceCountry],
            audience_genders: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::AudienceGender],
            audience_types: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::AudienceType],
            average_time_watched: Float,
            comments: Float,
            email_clicks: Float,
            engagement_likes: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::EngagementLike],
            favorites: Float,
            full_video_watched_rate: Float,
            impression_sources: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::ImpressionSource],
            lead_submissions: Float,
            likes: Float,
            new_followers: Float,
            phone_number_clicks: Float,
            profile_views: Float,
            reach: Float,
            shares: Float,
            total_time_watched: Float,
            video_view_retention: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::VideoViewRetention],
            video_views: Float,
            website_clicks: Float
          }

        class TikTokBusinessMetricsDto < PostForMe::Internal::Type::BaseModel
          attr_accessor address_clicks: Float

          attr_accessor app_download_clicks: Float

          attr_accessor audience_cities: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::AudienceCity]

          attr_accessor audience_countries: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::AudienceCountry]

          attr_accessor audience_genders: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::AudienceGender]

          attr_accessor audience_types: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::AudienceType]

          attr_accessor average_time_watched: Float

          attr_accessor comments: Float

          attr_accessor email_clicks: Float

          attr_accessor engagement_likes: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::EngagementLike]

          attr_accessor favorites: Float

          attr_accessor full_video_watched_rate: Float

          attr_accessor impression_sources: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::ImpressionSource]

          attr_accessor lead_submissions: Float

          attr_accessor likes: Float

          attr_accessor new_followers: Float

          attr_accessor phone_number_clicks: Float

          attr_accessor profile_views: Float

          attr_accessor reach: Float

          attr_accessor shares: Float

          attr_accessor total_time_watched: Float

          attr_accessor video_view_retention: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::VideoViewRetention]

          attr_accessor video_views: Float

          attr_accessor website_clicks: Float

          def initialize: (
            address_clicks: Float,
            app_download_clicks: Float,
            audience_cities: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::AudienceCity],
            audience_countries: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::AudienceCountry],
            audience_genders: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::AudienceGender],
            audience_types: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::AudienceType],
            average_time_watched: Float,
            comments: Float,
            email_clicks: Float,
            engagement_likes: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::EngagementLike],
            favorites: Float,
            full_video_watched_rate: Float,
            impression_sources: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::ImpressionSource],
            lead_submissions: Float,
            likes: Float,
            new_followers: Float,
            phone_number_clicks: Float,
            profile_views: Float,
            reach: Float,
            shares: Float,
            total_time_watched: Float,
            video_view_retention: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::VideoViewRetention],
            video_views: Float,
            website_clicks: Float
          ) -> void

          def to_hash: -> {
            address_clicks: Float,
            app_download_clicks: Float,
            audience_cities: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::AudienceCity],
            audience_countries: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::AudienceCountry],
            audience_genders: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::AudienceGender],
            audience_types: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::AudienceType],
            average_time_watched: Float,
            comments: Float,
            email_clicks: Float,
            engagement_likes: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::EngagementLike],
            favorites: Float,
            full_video_watched_rate: Float,
            impression_sources: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::ImpressionSource],
            lead_submissions: Float,
            likes: Float,
            new_followers: Float,
            phone_number_clicks: Float,
            profile_views: Float,
            reach: Float,
            shares: Float,
            total_time_watched: Float,
            video_view_retention: ::Array[PostForMe::PlatformPost::Metrics::TikTokBusinessMetricsDto::VideoViewRetention],
            video_views: Float,
            website_clicks: Float
          }

          type audience_city = { city_name: String, percentage: Float }

          class AudienceCity < PostForMe::Internal::Type::BaseModel
            attr_accessor city_name: String

            attr_accessor percentage: Float

            def initialize: (city_name: String, percentage: Float) -> void

            def to_hash: -> { city_name: String, percentage: Float }
          end

          type audience_country = { country: String, percentage: Float }

          class AudienceCountry < PostForMe::Internal::Type::BaseModel
            attr_accessor country: String

            attr_accessor percentage: Float

            def initialize: (country: String, percentage: Float) -> void

            def to_hash: -> { country: String, percentage: Float }
          end

          type audience_gender = { gender: String, percentage: Float }

          class AudienceGender < PostForMe::Internal::Type::BaseModel
            attr_accessor gender: String

            attr_accessor percentage: Float

            def initialize: (gender: String, percentage: Float) -> void

            def to_hash: -> { gender: String, percentage: Float }
          end

          type audience_type = { percentage: Float, type: String }

          class AudienceType < PostForMe::Internal::Type::BaseModel
            attr_accessor percentage: Float

            attr_accessor type: String

            def initialize: (percentage: Float, type: String) -> void

            def to_hash: -> { percentage: Float, type: String }
          end

          type engagement_like = { percentage: Float, second: String }

          class EngagementLike < PostForMe::Internal::Type::BaseModel
            attr_accessor percentage: Float

            attr_accessor second: String

            def initialize: (percentage: Float, second: String) -> void

            def to_hash: -> { percentage: Float, second: String }
          end

          type impression_source =
            { impression_source: String, percentage: Float }

          class ImpressionSource < PostForMe::Internal::Type::BaseModel
            attr_accessor impression_source: String

            attr_accessor percentage: Float

            def initialize: (
              impression_source: String,
              percentage: Float
            ) -> void

            def to_hash: -> { impression_source: String, percentage: Float }
          end

          type video_view_retention = { percentage: Float, second: String }

          class VideoViewRetention < PostForMe::Internal::Type::BaseModel
            attr_accessor percentage: Float

            attr_accessor second: String

            def initialize: (percentage: Float, second: String) -> void

            def to_hash: -> { percentage: Float, second: String }
          end
        end

        type tik_tok_post_metrics_dto =
          {
            comment_count: Float,
            like_count: Float,
            share_count: Float,
            view_count: Float
          }

        class TikTokPostMetricsDto < PostForMe::Internal::Type::BaseModel
          attr_accessor comment_count: Float

          attr_accessor like_count: Float

          attr_accessor share_count: Float

          attr_accessor view_count: Float

          def initialize: (
            comment_count: Float,
            like_count: Float,
            share_count: Float,
            view_count: Float
          ) -> void

          def to_hash: -> {
            comment_count: Float,
            like_count: Float,
            share_count: Float,
            view_count: Float
          }
        end

        type instagram_post_metrics_dto =
          {
            comments: Float,
            follows: Float,
            ig_reels_avg_watch_time: Float,
            ig_reels_video_view_total_time: Float,
            likes: Float,
            navigation: Float,
            profile_activity: Float,
            profile_visits: Float,
            reach: Float,
            replies: Float,
            saved: Float,
            shares: Float,
            total_interactions: Float,
            views: Float
          }

        class InstagramPostMetricsDto < PostForMe::Internal::Type::BaseModel
          attr_reader comments: Float?

          def comments=: (Float) -> Float

          attr_reader follows: Float?

          def follows=: (Float) -> Float

          attr_reader ig_reels_avg_watch_time: Float?

          def ig_reels_avg_watch_time=: (Float) -> Float

          attr_reader ig_reels_video_view_total_time: Float?

          def ig_reels_video_view_total_time=: (Float) -> Float

          attr_reader likes: Float?

          def likes=: (Float) -> Float

          attr_reader navigation: Float?

          def navigation=: (Float) -> Float

          attr_reader profile_activity: Float?

          def profile_activity=: (Float) -> Float

          attr_reader profile_visits: Float?

          def profile_visits=: (Float) -> Float

          attr_reader reach: Float?

          def reach=: (Float) -> Float

          attr_reader replies: Float?

          def replies=: (Float) -> Float

          attr_reader saved: Float?

          def saved=: (Float) -> Float

          attr_reader shares: Float?

          def shares=: (Float) -> Float

          attr_reader total_interactions: Float?

          def total_interactions=: (Float) -> Float

          attr_reader views: Float?

          def views=: (Float) -> Float

          def initialize: (
            ?comments: Float,
            ?follows: Float,
            ?ig_reels_avg_watch_time: Float,
            ?ig_reels_video_view_total_time: Float,
            ?likes: Float,
            ?navigation: Float,
            ?profile_activity: Float,
            ?profile_visits: Float,
            ?reach: Float,
            ?replies: Float,
            ?saved: Float,
            ?shares: Float,
            ?total_interactions: Float,
            ?views: Float
          ) -> void

          def to_hash: -> {
            comments: Float,
            follows: Float,
            ig_reels_avg_watch_time: Float,
            ig_reels_video_view_total_time: Float,
            likes: Float,
            navigation: Float,
            profile_activity: Float,
            profile_visits: Float,
            reach: Float,
            replies: Float,
            saved: Float,
            shares: Float,
            total_interactions: Float,
            views: Float
          }
        end

        type you_tube_post_metrics_dto =
          {
            comments: Float,
            dislikes: Float,
            likes: Float,
            views: Float,
            annotation_clickable_impressions: Float,
            annotation_clicks: Float,
            annotation_click_through_rate: Float,
            annotation_closable_impressions: Float,
            annotation_close_rate: Float,
            annotation_closes: Float,
            annotation_impressions: Float,
            average_view_duration: Float,
            average_view_percentage: Float,
            card_click_rate: Float,
            card_clicks: Float,
            card_impressions: Float,
            card_teaser_click_rate: Float,
            card_teaser_clicks: Float,
            card_teaser_impressions: Float,
            engaged_views: Float,
            estimated_minutes_watched: Float,
            estimated_red_minutes_watched: Float,
            red_views: Float,
            shares: Float,
            subscribers_gained: Float,
            subscribers_lost: Float,
            videos_added_to_playlists: Float,
            videos_removed_from_playlists: Float
          }

        class YouTubePostMetricsDto < PostForMe::Internal::Type::BaseModel
          attr_accessor comments: Float

          attr_accessor dislikes: Float

          attr_accessor likes: Float

          attr_accessor views: Float

          attr_reader annotation_clickable_impressions: Float?

          def annotation_clickable_impressions=: (Float) -> Float

          attr_reader annotation_clicks: Float?

          def annotation_clicks=: (Float) -> Float

          attr_reader annotation_click_through_rate: Float?

          def annotation_click_through_rate=: (Float) -> Float

          attr_reader annotation_closable_impressions: Float?

          def annotation_closable_impressions=: (Float) -> Float

          attr_reader annotation_close_rate: Float?

          def annotation_close_rate=: (Float) -> Float

          attr_reader annotation_closes: Float?

          def annotation_closes=: (Float) -> Float

          attr_reader annotation_impressions: Float?

          def annotation_impressions=: (Float) -> Float

          attr_reader average_view_duration: Float?

          def average_view_duration=: (Float) -> Float

          attr_reader average_view_percentage: Float?

          def average_view_percentage=: (Float) -> Float

          attr_reader card_click_rate: Float?

          def card_click_rate=: (Float) -> Float

          attr_reader card_clicks: Float?

          def card_clicks=: (Float) -> Float

          attr_reader card_impressions: Float?

          def card_impressions=: (Float) -> Float

          attr_reader card_teaser_click_rate: Float?

          def card_teaser_click_rate=: (Float) -> Float

          attr_reader card_teaser_clicks: Float?

          def card_teaser_clicks=: (Float) -> Float

          attr_reader card_teaser_impressions: Float?

          def card_teaser_impressions=: (Float) -> Float

          attr_reader engaged_views: Float?

          def engaged_views=: (Float) -> Float

          attr_reader estimated_minutes_watched: Float?

          def estimated_minutes_watched=: (Float) -> Float

          attr_reader estimated_red_minutes_watched: Float?

          def estimated_red_minutes_watched=: (Float) -> Float

          attr_reader red_views: Float?

          def red_views=: (Float) -> Float

          attr_reader shares: Float?

          def shares=: (Float) -> Float

          attr_reader subscribers_gained: Float?

          def subscribers_gained=: (Float) -> Float

          attr_reader subscribers_lost: Float?

          def subscribers_lost=: (Float) -> Float

          attr_reader videos_added_to_playlists: Float?

          def videos_added_to_playlists=: (Float) -> Float

          attr_reader videos_removed_from_playlists: Float?

          def videos_removed_from_playlists=: (Float) -> Float

          def initialize: (
            comments: Float,
            dislikes: Float,
            likes: Float,
            views: Float,
            ?annotation_clickable_impressions: Float,
            ?annotation_clicks: Float,
            ?annotation_click_through_rate: Float,
            ?annotation_closable_impressions: Float,
            ?annotation_close_rate: Float,
            ?annotation_closes: Float,
            ?annotation_impressions: Float,
            ?average_view_duration: Float,
            ?average_view_percentage: Float,
            ?card_click_rate: Float,
            ?card_clicks: Float,
            ?card_impressions: Float,
            ?card_teaser_click_rate: Float,
            ?card_teaser_clicks: Float,
            ?card_teaser_impressions: Float,
            ?engaged_views: Float,
            ?estimated_minutes_watched: Float,
            ?estimated_red_minutes_watched: Float,
            ?red_views: Float,
            ?shares: Float,
            ?subscribers_gained: Float,
            ?subscribers_lost: Float,
            ?videos_added_to_playlists: Float,
            ?videos_removed_from_playlists: Float
          ) -> void

          def to_hash: -> {
            comments: Float,
            dislikes: Float,
            likes: Float,
            views: Float,
            annotation_clickable_impressions: Float,
            annotation_clicks: Float,
            annotation_click_through_rate: Float,
            annotation_closable_impressions: Float,
            annotation_close_rate: Float,
            annotation_closes: Float,
            annotation_impressions: Float,
            average_view_duration: Float,
            average_view_percentage: Float,
            card_click_rate: Float,
            card_clicks: Float,
            card_impressions: Float,
            card_teaser_click_rate: Float,
            card_teaser_clicks: Float,
            card_teaser_impressions: Float,
            engaged_views: Float,
            estimated_minutes_watched: Float,
            estimated_red_minutes_watched: Float,
            red_views: Float,
            shares: Float,
            subscribers_gained: Float,
            subscribers_lost: Float,
            videos_added_to_playlists: Float,
            videos_removed_from_playlists: Float
          }
        end

        type facebook_post_metrics_dto =
          {
            activity_by_action_type: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::ActivityByActionType],
            activity_by_action_type_unique: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::ActivityByActionTypeUnique],
            comments: Float,
            fan_reach: Float,
            media_views: Float,
            nonviral_reach: Float,
            organic_reach: Float,
            paid_reach: Float,
            reach: Float,
            reactions_anger: Float,
            reactions_by_type: top,
            reactions_haha: Float,
            reactions_like: Float,
            reactions_love: Float,
            reactions_sorry: Float,
            reactions_total: Float,
            reactions_wow: Float,
            shares: Float,
            video_avg_time_watched: Float,
            video_complete_views_organic: Float,
            video_complete_views_organic_unique: Float,
            video_complete_views_paid: Float,
            video_complete_views_paid_unique: Float,
            video_length: Float,
            video_retention_graph_autoplayed: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoRetentionGraphAutoplayed],
            video_retention_graph_clicked_to_play: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoRetentionGraphClickedToPlay],
            video_social_actions_unique: Float,
            video_view_time: Float,
            video_view_time_by_age_gender: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoViewTimeByAgeGender],
            video_view_time_by_country: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoViewTimeByCountry],
            video_view_time_by_distribution_type: top,
            video_view_time_by_region: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoViewTimeByRegion],
            video_view_time_organic: Float,
            video_views: Float,
            :video_views_15s => Float,
            :video_views_60s => Float,
            video_views_autoplayed: Float,
            video_views_by_distribution_type: top,
            video_views_clicked_to_play: Float,
            video_views_organic: Float,
            video_views_organic_unique: Float,
            video_views_paid: Float,
            video_views_paid_unique: Float,
            video_views_sound_on: Float,
            video_views_unique: Float,
            viral_reach: Float
          }

        class FacebookPostMetricsDto < PostForMe::Internal::Type::BaseModel
          attr_reader activity_by_action_type: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::ActivityByActionType]?

          def activity_by_action_type=: (
            ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::ActivityByActionType]
          ) -> ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::ActivityByActionType]

          attr_reader activity_by_action_type_unique: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::ActivityByActionTypeUnique]?

          def activity_by_action_type_unique=: (
            ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::ActivityByActionTypeUnique]
          ) -> ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::ActivityByActionTypeUnique]

          attr_reader comments: Float?

          def comments=: (Float) -> Float

          attr_reader fan_reach: Float?

          def fan_reach=: (Float) -> Float

          attr_reader media_views: Float?

          def media_views=: (Float) -> Float

          attr_reader nonviral_reach: Float?

          def nonviral_reach=: (Float) -> Float

          attr_reader organic_reach: Float?

          def organic_reach=: (Float) -> Float

          attr_reader paid_reach: Float?

          def paid_reach=: (Float) -> Float

          attr_reader reach: Float?

          def reach=: (Float) -> Float

          attr_reader reactions_anger: Float?

          def reactions_anger=: (Float) -> Float

          attr_reader reactions_by_type: top?

          def reactions_by_type=: (top) -> top

          attr_reader reactions_haha: Float?

          def reactions_haha=: (Float) -> Float

          attr_reader reactions_like: Float?

          def reactions_like=: (Float) -> Float

          attr_reader reactions_love: Float?

          def reactions_love=: (Float) -> Float

          attr_reader reactions_sorry: Float?

          def reactions_sorry=: (Float) -> Float

          attr_reader reactions_total: Float?

          def reactions_total=: (Float) -> Float

          attr_reader reactions_wow: Float?

          def reactions_wow=: (Float) -> Float

          attr_reader shares: Float?

          def shares=: (Float) -> Float

          attr_reader video_avg_time_watched: Float?

          def video_avg_time_watched=: (Float) -> Float

          attr_reader video_complete_views_organic: Float?

          def video_complete_views_organic=: (Float) -> Float

          attr_reader video_complete_views_organic_unique: Float?

          def video_complete_views_organic_unique=: (Float) -> Float

          attr_reader video_complete_views_paid: Float?

          def video_complete_views_paid=: (Float) -> Float

          attr_reader video_complete_views_paid_unique: Float?

          def video_complete_views_paid_unique=: (Float) -> Float

          attr_reader video_length: Float?

          def video_length=: (Float) -> Float

          attr_reader video_retention_graph_autoplayed: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoRetentionGraphAutoplayed]?

          def video_retention_graph_autoplayed=: (
            ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoRetentionGraphAutoplayed]
          ) -> ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoRetentionGraphAutoplayed]

          attr_reader video_retention_graph_clicked_to_play: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoRetentionGraphClickedToPlay]?

          def video_retention_graph_clicked_to_play=: (
            ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoRetentionGraphClickedToPlay]
          ) -> ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoRetentionGraphClickedToPlay]

          attr_reader video_social_actions_unique: Float?

          def video_social_actions_unique=: (Float) -> Float

          attr_reader video_view_time: Float?

          def video_view_time=: (Float) -> Float

          attr_reader video_view_time_by_age_gender: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoViewTimeByAgeGender]?

          def video_view_time_by_age_gender=: (
            ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoViewTimeByAgeGender]
          ) -> ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoViewTimeByAgeGender]

          attr_reader video_view_time_by_country: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoViewTimeByCountry]?

          def video_view_time_by_country=: (
            ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoViewTimeByCountry]
          ) -> ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoViewTimeByCountry]

          attr_reader video_view_time_by_distribution_type: top?

          def video_view_time_by_distribution_type=: (top) -> top

          attr_reader video_view_time_by_region: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoViewTimeByRegion]?

          def video_view_time_by_region=: (
            ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoViewTimeByRegion]
          ) -> ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoViewTimeByRegion]

          attr_reader video_view_time_organic: Float?

          def video_view_time_organic=: (Float) -> Float

          attr_reader video_views: Float?

          def video_views=: (Float) -> Float

          attr_reader video_views_15s: Float?

          def video_views_15s=: (Float) -> Float

          attr_reader video_views_60s: Float?

          def video_views_60s=: (Float) -> Float

          attr_reader video_views_autoplayed: Float?

          def video_views_autoplayed=: (Float) -> Float

          attr_reader video_views_by_distribution_type: top?

          def video_views_by_distribution_type=: (top) -> top

          attr_reader video_views_clicked_to_play: Float?

          def video_views_clicked_to_play=: (Float) -> Float

          attr_reader video_views_organic: Float?

          def video_views_organic=: (Float) -> Float

          attr_reader video_views_organic_unique: Float?

          def video_views_organic_unique=: (Float) -> Float

          attr_reader video_views_paid: Float?

          def video_views_paid=: (Float) -> Float

          attr_reader video_views_paid_unique: Float?

          def video_views_paid_unique=: (Float) -> Float

          attr_reader video_views_sound_on: Float?

          def video_views_sound_on=: (Float) -> Float

          attr_reader video_views_unique: Float?

          def video_views_unique=: (Float) -> Float

          attr_reader viral_reach: Float?

          def viral_reach=: (Float) -> Float

          def initialize: (
            ?activity_by_action_type: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::ActivityByActionType],
            ?activity_by_action_type_unique: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::ActivityByActionTypeUnique],
            ?comments: Float,
            ?fan_reach: Float,
            ?media_views: Float,
            ?nonviral_reach: Float,
            ?organic_reach: Float,
            ?paid_reach: Float,
            ?reach: Float,
            ?reactions_anger: Float,
            ?reactions_by_type: top,
            ?reactions_haha: Float,
            ?reactions_like: Float,
            ?reactions_love: Float,
            ?reactions_sorry: Float,
            ?reactions_total: Float,
            ?reactions_wow: Float,
            ?shares: Float,
            ?video_avg_time_watched: Float,
            ?video_complete_views_organic: Float,
            ?video_complete_views_organic_unique: Float,
            ?video_complete_views_paid: Float,
            ?video_complete_views_paid_unique: Float,
            ?video_length: Float,
            ?video_retention_graph_autoplayed: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoRetentionGraphAutoplayed],
            ?video_retention_graph_clicked_to_play: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoRetentionGraphClickedToPlay],
            ?video_social_actions_unique: Float,
            ?video_view_time: Float,
            ?video_view_time_by_age_gender: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoViewTimeByAgeGender],
            ?video_view_time_by_country: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoViewTimeByCountry],
            ?video_view_time_by_distribution_type: top,
            ?video_view_time_by_region: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoViewTimeByRegion],
            ?video_view_time_organic: Float,
            ?video_views: Float,
            ?video_views_15s: Float,
            ?video_views_60s: Float,
            ?video_views_autoplayed: Float,
            ?video_views_by_distribution_type: top,
            ?video_views_clicked_to_play: Float,
            ?video_views_organic: Float,
            ?video_views_organic_unique: Float,
            ?video_views_paid: Float,
            ?video_views_paid_unique: Float,
            ?video_views_sound_on: Float,
            ?video_views_unique: Float,
            ?viral_reach: Float
          ) -> void

          def to_hash: -> {
            activity_by_action_type: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::ActivityByActionType],
            activity_by_action_type_unique: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::ActivityByActionTypeUnique],
            comments: Float,
            fan_reach: Float,
            media_views: Float,
            nonviral_reach: Float,
            organic_reach: Float,
            paid_reach: Float,
            reach: Float,
            reactions_anger: Float,
            reactions_by_type: top,
            reactions_haha: Float,
            reactions_like: Float,
            reactions_love: Float,
            reactions_sorry: Float,
            reactions_total: Float,
            reactions_wow: Float,
            shares: Float,
            video_avg_time_watched: Float,
            video_complete_views_organic: Float,
            video_complete_views_organic_unique: Float,
            video_complete_views_paid: Float,
            video_complete_views_paid_unique: Float,
            video_length: Float,
            video_retention_graph_autoplayed: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoRetentionGraphAutoplayed],
            video_retention_graph_clicked_to_play: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoRetentionGraphClickedToPlay],
            video_social_actions_unique: Float,
            video_view_time: Float,
            video_view_time_by_age_gender: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoViewTimeByAgeGender],
            video_view_time_by_country: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoViewTimeByCountry],
            video_view_time_by_distribution_type: top,
            video_view_time_by_region: ::Array[PostForMe::PlatformPost::Metrics::FacebookPostMetricsDto::VideoViewTimeByRegion],
            video_view_time_organic: Float,
            video_views: Float,
            :video_views_15s => Float,
            :video_views_60s => Float,
            video_views_autoplayed: Float,
            video_views_by_distribution_type: top,
            video_views_clicked_to_play: Float,
            video_views_organic: Float,
            video_views_organic_unique: Float,
            video_views_paid: Float,
            video_views_paid_unique: Float,
            video_views_sound_on: Float,
            video_views_unique: Float,
            viral_reach: Float
          }

          type activity_by_action_type = { action_type: String, value: Float }

          class ActivityByActionType < PostForMe::Internal::Type::BaseModel
            attr_accessor action_type: String

            attr_accessor value: Float

            def initialize: (action_type: String, value: Float) -> void

            def to_hash: -> { action_type: String, value: Float }
          end

          type activity_by_action_type_unique =
            { action_type: String, value: Float }

          class ActivityByActionTypeUnique < PostForMe::Internal::Type::BaseModel
            attr_accessor action_type: String

            attr_accessor value: Float

            def initialize: (action_type: String, value: Float) -> void

            def to_hash: -> { action_type: String, value: Float }
          end

          type video_retention_graph_autoplayed = { rate: Float, time: Float }

          class VideoRetentionGraphAutoplayed < PostForMe::Internal::Type::BaseModel
            attr_accessor rate: Float

            attr_accessor time: Float

            def initialize: (rate: Float, time: Float) -> void

            def to_hash: -> { rate: Float, time: Float }
          end

          type video_retention_graph_clicked_to_play =
            { rate: Float, time: Float }

          class VideoRetentionGraphClickedToPlay < PostForMe::Internal::Type::BaseModel
            attr_accessor rate: Float

            attr_accessor time: Float

            def initialize: (rate: Float, time: Float) -> void

            def to_hash: -> { rate: Float, time: Float }
          end

          type video_view_time_by_age_gender = { key: String, value: Float }

          class VideoViewTimeByAgeGender < PostForMe::Internal::Type::BaseModel
            attr_accessor key: String

            attr_accessor value: Float

            def initialize: (key: String, value: Float) -> void

            def to_hash: -> { key: String, value: Float }
          end

          type video_view_time_by_country = { key: String, value: Float }

          class VideoViewTimeByCountry < PostForMe::Internal::Type::BaseModel
            attr_accessor key: String

            attr_accessor value: Float

            def initialize: (key: String, value: Float) -> void

            def to_hash: -> { key: String, value: Float }
          end

          type video_view_time_by_region = { key: String, value: Float }

          class VideoViewTimeByRegion < PostForMe::Internal::Type::BaseModel
            attr_accessor key: String

            attr_accessor value: Float

            def initialize: (key: String, value: Float) -> void

            def to_hash: -> { key: String, value: Float }
          end
        end

        type twitter_post_metrics_dto =
          {
            non_public_metrics: PostForMe::PlatformPost::Metrics::TwitterPostMetricsDto::NonPublicMetrics,
            organic_metrics: PostForMe::PlatformPost::Metrics::TwitterPostMetricsDto::OrganicMetrics,
            public_metrics: PostForMe::PlatformPost::Metrics::TwitterPostMetricsDto::PublicMetrics
          }

        class TwitterPostMetricsDto < PostForMe::Internal::Type::BaseModel
          attr_reader non_public_metrics: PostForMe::PlatformPost::Metrics::TwitterPostMetricsDto::NonPublicMetrics?

          def non_public_metrics=: (
            PostForMe::PlatformPost::Metrics::TwitterPostMetricsDto::NonPublicMetrics
          ) -> PostForMe::PlatformPost::Metrics::TwitterPostMetricsDto::NonPublicMetrics

          attr_reader organic_metrics: PostForMe::PlatformPost::Metrics::TwitterPostMetricsDto::OrganicMetrics?

          def organic_metrics=: (
            PostForMe::PlatformPost::Metrics::TwitterPostMetricsDto::OrganicMetrics
          ) -> PostForMe::PlatformPost::Metrics::TwitterPostMetricsDto::OrganicMetrics

          attr_reader public_metrics: PostForMe::PlatformPost::Metrics::TwitterPostMetricsDto::PublicMetrics?

          def public_metrics=: (
            PostForMe::PlatformPost::Metrics::TwitterPostMetricsDto::PublicMetrics
          ) -> PostForMe::PlatformPost::Metrics::TwitterPostMetricsDto::PublicMetrics

          def initialize: (
            ?non_public_metrics: PostForMe::PlatformPost::Metrics::TwitterPostMetricsDto::NonPublicMetrics,
            ?organic_metrics: PostForMe::PlatformPost::Metrics::TwitterPostMetricsDto::OrganicMetrics,
            ?public_metrics: PostForMe::PlatformPost::Metrics::TwitterPostMetricsDto::PublicMetrics
          ) -> void

          def to_hash: -> {
            non_public_metrics: PostForMe::PlatformPost::Metrics::TwitterPostMetricsDto::NonPublicMetrics,
            organic_metrics: PostForMe::PlatformPost::Metrics::TwitterPostMetricsDto::OrganicMetrics,
            public_metrics: PostForMe::PlatformPost::Metrics::TwitterPostMetricsDto::PublicMetrics
          }

          type non_public_metrics =
            {
              impression_count: Float,
              url_link_clicks: Float,
              user_profile_clicks: Float
            }

          class NonPublicMetrics < PostForMe::Internal::Type::BaseModel
            attr_accessor impression_count: Float

            attr_accessor url_link_clicks: Float

            attr_accessor user_profile_clicks: Float

            def initialize: (
              impression_count: Float,
              url_link_clicks: Float,
              user_profile_clicks: Float
            ) -> void

            def to_hash: -> {
              impression_count: Float,
              url_link_clicks: Float,
              user_profile_clicks: Float
            }
          end

          type organic_metrics =
            {
              impression_count: Float,
              like_count: Float,
              reply_count: Float,
              retweet_count: Float,
              url_link_clicks: Float,
              user_profile_clicks: Float
            }

          class OrganicMetrics < PostForMe::Internal::Type::BaseModel
            attr_accessor impression_count: Float

            attr_accessor like_count: Float

            attr_accessor reply_count: Float

            attr_accessor retweet_count: Float

            attr_accessor url_link_clicks: Float

            attr_accessor user_profile_clicks: Float

            def initialize: (
              impression_count: Float,
              like_count: Float,
              reply_count: Float,
              retweet_count: Float,
              url_link_clicks: Float,
              user_profile_clicks: Float
            ) -> void

            def to_hash: -> {
              impression_count: Float,
              like_count: Float,
              reply_count: Float,
              retweet_count: Float,
              url_link_clicks: Float,
              user_profile_clicks: Float
            }
          end

          type public_metrics =
            {
              bookmark_count: Float,
              impression_count: Float,
              like_count: Float,
              quote_count: Float,
              reply_count: Float,
              retweet_count: Float
            }

          class PublicMetrics < PostForMe::Internal::Type::BaseModel
            attr_accessor bookmark_count: Float

            attr_accessor impression_count: Float

            attr_accessor like_count: Float

            attr_accessor quote_count: Float

            attr_accessor reply_count: Float

            attr_accessor retweet_count: Float

            def initialize: (
              bookmark_count: Float,
              impression_count: Float,
              like_count: Float,
              quote_count: Float,
              reply_count: Float,
              retweet_count: Float
            ) -> void

            def to_hash: -> {
              bookmark_count: Float,
              impression_count: Float,
              like_count: Float,
              quote_count: Float,
              reply_count: Float,
              retweet_count: Float
            }
          end
        end

        type threads_post_metrics_dto =
          {
            likes: Float,
            quotes: Float,
            replies: Float,
            reposts: Float,
            shares: Float,
            views: Float
          }

        class ThreadsPostMetricsDto < PostForMe::Internal::Type::BaseModel
          attr_accessor likes: Float

          attr_accessor quotes: Float

          attr_accessor replies: Float

          attr_accessor reposts: Float

          attr_accessor shares: Float

          attr_accessor views: Float

          def initialize: (
            likes: Float,
            quotes: Float,
            replies: Float,
            reposts: Float,
            shares: Float,
            views: Float
          ) -> void

          def to_hash: -> {
            likes: Float,
            quotes: Float,
            replies: Float,
            reposts: Float,
            shares: Float,
            views: Float
          }
        end

        def self?.variants: -> ::Array[PostForMe::Models::PlatformPost::metrics]
      end
    end
  end
end
