module PostForMe
  module Models
    type social_account_disconnect_params =
      { id: String } & PostForMe::Internal::Type::request_parameters

    class SocialAccountDisconnectParams < PostForMe::Internal::Type::BaseModel
      extend PostForMe::Internal::Type::RequestParameters::Converter
      include PostForMe::Internal::Type::RequestParameters

      attr_accessor id: String

      def initialize: (
        id: String,
        ?request_options: PostForMe::request_opts
      ) -> void

      def to_hash: -> { id: String, request_options: PostForMe::RequestOptions }
    end
  end
end
