module PostForMe
  module Models
    type social_account =
      {
        id: String,
        access_token: String,
        access_token_expires_at: Time,
        external_id: String?,
        metadata: top?,
        platform: String,
        profile_photo_url: String?,
        refresh_token: String?,
        refresh_token_expires_at: Time?,
        status: PostForMe::Models::SocialAccount::status,
        user_id: String,
        username: String?
      }

    class SocialAccount < PostForMe::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor access_token: String

      attr_accessor access_token_expires_at: Time

      attr_accessor external_id: String?

      attr_accessor metadata: top?

      attr_accessor platform: String

      attr_accessor profile_photo_url: String?

      attr_accessor refresh_token: String?

      attr_accessor refresh_token_expires_at: Time?

      attr_accessor status: PostForMe::Models::SocialAccount::status

      attr_accessor user_id: String

      attr_accessor username: String?

      def initialize: (
        id: String,
        access_token: String,
        access_token_expires_at: Time,
        external_id: String?,
        metadata: top?,
        platform: String,
        profile_photo_url: String?,
        refresh_token: String?,
        refresh_token_expires_at: Time?,
        status: PostForMe::Models::SocialAccount::status,
        user_id: String,
        username: String?
      ) -> void

      def to_hash: -> {
        id: String,
        access_token: String,
        access_token_expires_at: Time,
        external_id: String?,
        metadata: top?,
        platform: String,
        profile_photo_url: String?,
        refresh_token: String?,
        refresh_token_expires_at: Time?,
        status: PostForMe::Models::SocialAccount::status,
        user_id: String,
        username: String?
      }

      type status = :connected | :disconnected

      module Status
        extend PostForMe::Internal::Type::Enum

        CONNECTED: :connected
        DISCONNECTED: :disconnected

        def self?.values: -> ::Array[PostForMe::Models::SocialAccount::status]
      end
    end
  end
end
