module PostForMe
  module Models
    type social_post_list_response =
      {
        data: ::Array[PostForMe::SocialPost],
        meta: PostForMe::Models::SocialPostListResponse::Meta
      }

    class SocialPostListResponse < PostForMe::Internal::Type::BaseModel
      attr_accessor data: ::Array[PostForMe::SocialPost]

      attr_accessor meta: PostForMe::Models::SocialPostListResponse::Meta

      def initialize: (
        data: ::Array[PostForMe::SocialPost],
        meta: PostForMe::Models::SocialPostListResponse::Meta
      ) -> void

      def to_hash: -> {
        data: ::Array[PostForMe::SocialPost],
        meta: PostForMe::Models::SocialPostListResponse::Meta
      }

      type meta = { limit: Float, next_: String?, offset: Float, total: Float }

      class Meta < PostForMe::Internal::Type::BaseModel
        attr_accessor limit: Float

        attr_accessor next_: String?

        attr_accessor offset: Float

        attr_accessor total: Float

        def initialize: (
          limit: Float,
          next_: String?,
          offset: Float,
          total: Float
        ) -> void

        def to_hash: -> {
          limit: Float,
          next_: String?,
          offset: Float,
          total: Float
        }
      end
    end
  end
end
