module PostForMe
  module Models
    type twitter_configuration_dto =
      {
        caption: top?,
        community_id: String,
        media: ::Array[PostForMe::SocialPostMedia]?,
        poll: PostForMe::TwitterPoll,
        quote_tweet_id: String,
        reply_settings: PostForMe::Models::TwitterConfigurationDto::reply_settings?
      }

    class TwitterConfigurationDto < PostForMe::Internal::Type::BaseModel
      attr_accessor caption: top?

      attr_reader community_id: String?

      def community_id=: (String) -> String

      attr_accessor media: ::Array[PostForMe::SocialPostMedia]?

      attr_reader poll: PostForMe::TwitterPoll?

      def poll=: (PostForMe::TwitterPoll) -> PostForMe::TwitterPoll

      attr_reader quote_tweet_id: String?

      def quote_tweet_id=: (String) -> String

      attr_accessor reply_settings: PostForMe::Models::TwitterConfigurationDto::reply_settings?

      def initialize: (
        ?caption: top?,
        ?community_id: String,
        ?media: ::Array[PostForMe::SocialPostMedia]?,
        ?poll: PostForMe::TwitterPoll,
        ?quote_tweet_id: String,
        ?reply_settings: PostForMe::Models::TwitterConfigurationDto::reply_settings?
      ) -> void

      def to_hash: -> {
        caption: top?,
        community_id: String,
        media: ::Array[PostForMe::SocialPostMedia]?,
        poll: PostForMe::TwitterPoll,
        quote_tweet_id: String,
        reply_settings: PostForMe::Models::TwitterConfigurationDto::reply_settings?
      }

      type reply_settings =
        :following | :mentionedUsers | :subscribers | :verified

      module ReplySettings
        extend PostForMe::Internal::Type::Enum

        FOLLOWING: :following
        MENTIONED_USERS: :mentionedUsers
        SUBSCRIBERS: :subscribers
        VERIFIED: :verified

        def self?.values: -> ::Array[PostForMe::Models::TwitterConfigurationDto::reply_settings]
      end
    end
  end
end
