module PostForMe
  module Models
    type webhook_list_params =
      {
        id: ::Array[String],
        event_type: ::Array[String],
        limit: Float,
        offset: Float,
        url: ::Array[String]
      }
      & PostForMe::Internal::Type::request_parameters

    class WebhookListParams < PostForMe::Internal::Type::BaseModel
      extend PostForMe::Internal::Type::RequestParameters::Converter
      include PostForMe::Internal::Type::RequestParameters

      attr_reader id: ::Array[String]?

      def id=: (::Array[String]) -> ::Array[String]

      attr_reader event_type: ::Array[String]?

      def event_type=: (::Array[String]) -> ::Array[String]

      attr_reader limit: Float?

      def limit=: (Float) -> Float

      attr_reader offset: Float?

      def offset=: (Float) -> Float

      attr_reader url: ::Array[String]?

      def url=: (::Array[String]) -> ::Array[String]

      def initialize: (
        ?id: ::Array[String],
        ?event_type: ::Array[String],
        ?limit: Float,
        ?offset: Float,
        ?url: ::Array[String],
        ?request_options: PostForMe::request_opts
      ) -> void

      def to_hash: -> {
        id: ::Array[String],
        event_type: ::Array[String],
        limit: Float,
        offset: Float,
        url: ::Array[String],
        request_options: PostForMe::RequestOptions
      }
    end
  end
end
