module PostForMe
  module Models
    type youtube_configuration_dto =
      {
        caption: top?,
        media: ::Array[PostForMe::YoutubeConfigurationDto::Media]?,
        title: String?
      }

    class YoutubeConfigurationDto < PostForMe::Internal::Type::BaseModel
      attr_accessor caption: top?

      attr_accessor media: ::Array[PostForMe::YoutubeConfigurationDto::Media]?

      attr_accessor title: String?

      def initialize: (
        ?caption: top?,
        ?media: ::Array[PostForMe::YoutubeConfigurationDto::Media]?,
        ?title: String?
      ) -> void

      def to_hash: -> {
        caption: top?,
        media: ::Array[PostForMe::YoutubeConfigurationDto::Media]?,
        title: String?
      }

      type media =
        { url: String, thumbnail_timestamp_ms: top?, thumbnail_url: top? }

      class Media < PostForMe::Internal::Type::BaseModel
        attr_accessor url: String

        attr_accessor thumbnail_timestamp_ms: top?

        attr_accessor thumbnail_url: top?

        def initialize: (
          url: String,
          ?thumbnail_timestamp_ms: top?,
          ?thumbnail_url: top?
        ) -> void

        def to_hash: -> {
          url: String,
          thumbnail_timestamp_ms: top?,
          thumbnail_url: top?
        }
      end
    end
  end
end
