module PostForMe
  class BlueskyConfigurationDto = PostForMe::Models::BlueskyConfigurationDto

  class CreateSocialPost = PostForMe::Models::CreateSocialPost

  class FacebookConfigurationDto = PostForMe::Models::FacebookConfigurationDto

  class InstagramConfigurationDto = PostForMe::Models::InstagramConfigurationDto

  class LinkedinConfigurationDto = PostForMe::Models::LinkedinConfigurationDto

  class MediaCreateUploadURLParams = PostForMe::Models::MediaCreateUploadURLParams

  class PinterestConfigurationDto = PostForMe::Models::PinterestConfigurationDto

  class PlatformConfigurationsDto = PostForMe::Models::PlatformConfigurationsDto

  class PlatformPost = PostForMe::Models::PlatformPost

  class SocialAccount = PostForMe::Models::SocialAccount

  class SocialAccountCreateAuthURLParams = PostForMe::Models::SocialAccountCreateAuthURLParams

  class SocialAccountCreateParams = PostForMe::Models::SocialAccountCreateParams

  class SocialAccountDisconnectParams = PostForMe::Models::SocialAccountDisconnectParams

  class SocialAccountFeedListParams = PostForMe::Models::SocialAccountFeedListParams

  class SocialAccountListParams = PostForMe::Models::SocialAccountListParams

  class SocialAccountRetrieveParams = PostForMe::Models::SocialAccountRetrieveParams

  class SocialAccountUpdateParams = PostForMe::Models::SocialAccountUpdateParams

  class SocialPost = PostForMe::Models::SocialPost

  class SocialPostCreateParams = PostForMe::Models::SocialPostCreateParams

  class SocialPostDeleteParams = PostForMe::Models::SocialPostDeleteParams

  class SocialPostListParams = PostForMe::Models::SocialPostListParams

  class SocialPostResult = PostForMe::Models::SocialPostResult

  class SocialPostResultListParams = PostForMe::Models::SocialPostResultListParams

  class SocialPostResultRetrieveParams = PostForMe::Models::SocialPostResultRetrieveParams

  class SocialPostRetrieveParams = PostForMe::Models::SocialPostRetrieveParams

  class SocialPostUpdateParams = PostForMe::Models::SocialPostUpdateParams

  class ThreadsConfigurationDto = PostForMe::Models::ThreadsConfigurationDto

  class TiktokConfiguration = PostForMe::Models::TiktokConfiguration

  class TwitterConfigurationDto = PostForMe::Models::TwitterConfigurationDto

  class YoutubeConfigurationDto = PostForMe::Models::YoutubeConfigurationDto
end
