module PostForMe
  class AccountConfiguration = PostForMe::Models::AccountConfiguration

  class BlueskyConfigurationDto = PostForMe::Models::BlueskyConfigurationDto

  class CreateSocialPost = PostForMe::Models::CreateSocialPost

  class CreateSocialPostPreview = PostForMe::Models::CreateSocialPostPreview

  class DeleteEntityResponse = PostForMe::Models::DeleteEntityResponse

  class FacebookActivityByActionType = PostForMe::Models::FacebookActivityByActionType

  class FacebookConfigurationDto = PostForMe::Models::FacebookConfigurationDto

  class FacebookVideoRetentionGraph = PostForMe::Models::FacebookVideoRetentionGraph

  class FacebookVideoViewTimeByDemographic = PostForMe::Models::FacebookVideoViewTimeByDemographic

  class InstagramConfigurationDto = PostForMe::Models::InstagramConfigurationDto

  class LinkedinConfigurationDto = PostForMe::Models::LinkedinConfigurationDto

  class MediaCreateUploadURLParams = PostForMe::Models::MediaCreateUploadURLParams

  class PinterestConfigurationDto = PostForMe::Models::PinterestConfigurationDto

  class PinterestMetricsWindow = PostForMe::Models::PinterestMetricsWindow

  class PlatformConfigurationsDto = PostForMe::Models::PlatformConfigurationsDto

  class PlatformPost = PostForMe::Models::PlatformPost

  class SocialAccount = PostForMe::Models::SocialAccount

  class SocialAccountCreateAuthURLParams = PostForMe::Models::SocialAccountCreateAuthURLParams

  class SocialAccountCreateParams = PostForMe::Models::SocialAccountCreateParams

  class SocialAccountDisconnectParams = PostForMe::Models::SocialAccountDisconnectParams

  class SocialAccountFeedListParams = PostForMe::Models::SocialAccountFeedListParams

  class SocialAccountListParams = PostForMe::Models::SocialAccountListParams

  SocialAccountMetadata: PostForMe::Internal::Type::Converter

  class SocialAccountRetrieveParams = PostForMe::Models::SocialAccountRetrieveParams

  class SocialAccountUpdateParams = PostForMe::Models::SocialAccountUpdateParams

  class SocialPost = PostForMe::Models::SocialPost

  class SocialPostCreateParams = PostForMe::Models::SocialPostCreateParams

  class SocialPostDeleteParams = PostForMe::Models::SocialPostDeleteParams

  class SocialPostListParams = PostForMe::Models::SocialPostListParams

  class SocialPostMedia = PostForMe::Models::SocialPostMedia

  class SocialPostPreview = PostForMe::Models::SocialPostPreview

  class SocialPostPreviewCreateParams = PostForMe::Models::SocialPostPreviewCreateParams

  class SocialPostResult = PostForMe::Models::SocialPostResult

  class SocialPostResultListParams = PostForMe::Models::SocialPostResultListParams

  class SocialPostResultRetrieveParams = PostForMe::Models::SocialPostResultRetrieveParams

  class SocialPostRetrieveParams = PostForMe::Models::SocialPostRetrieveParams

  class SocialPostUpdateParams = PostForMe::Models::SocialPostUpdateParams

  class ThreadsConfigurationDto = PostForMe::Models::ThreadsConfigurationDto

  class TiktokBusinessVideoMetricPercentage = PostForMe::Models::TiktokBusinessVideoMetricPercentage

  class TiktokConfiguration = PostForMe::Models::TiktokConfiguration

  class TwitterConfigurationDto = PostForMe::Models::TwitterConfigurationDto

  class TwitterPoll = PostForMe::Models::TwitterPoll

  class Webhook = PostForMe::Models::Webhook

  class WebhookCreateParams = PostForMe::Models::WebhookCreateParams

  class WebhookDeleteParams = PostForMe::Models::WebhookDeleteParams

  class WebhookListParams = PostForMe::Models::WebhookListParams

  class WebhookRetrieveParams = PostForMe::Models::WebhookRetrieveParams

  class WebhookUpdateParams = PostForMe::Models::WebhookUpdateParams

  class YoutubeConfigurationDto = PostForMe::Models::YoutubeConfigurationDto

  class YoutubePostPlatformData = PostForMe::Models::YoutubePostPlatformData
end
