module PostForMe
  module Resources
    class SocialPostPreviews
      def create: (
        caption: String,
        preview_social_accounts: ::Array[PostForMe::CreateSocialPostPreview::PreviewSocialAccount],
        ?account_configurations: ::Array[PostForMe::AccountConfiguration]?,
        ?media: ::Array[PostForMe::SocialPostMedia]?,
        ?platform_configurations: PostForMe::PlatformConfigurationsDto?,
        ?request_options: PostForMe::request_opts
      ) -> PostForMe::Models::social_post_preview_create_response

      def initialize: (client: PostForMe::Client) -> void
    end
  end
end
